ALTER TABLE QRTZ_GROUP ADD `UNIT_ID` bigint(64) DEFAULT null  COMMENT '单位ID';


ALTER TABLE SYS_ORGANIZER ADD `LONGITUDE` decimal(10,6) DEFAULT '0' COMMENT '经度';
ALTER TABLE SYS_ORGANIZER ADD `LATITUDE` decimal(10,6) DEFAULT '0' COMMENT '纬度';

ALTER TABLE SYS_ORGANIZER ADD `ORGANIZER_CODE` varchar(100) DEFAULT NULL COMMENT '编号';

ALTER TABLE SYS_USER ADD `C_UNIT_ID` bigint(64) DEFAULT NULL COMMENT '单位ID';
update SYS_USER set C_UNIT_ID = '2' where C_USER_ID = '1077874329775038466';

